# Generated by Django 4.2.16 on 2025-02-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVideojuegos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consola',
            name='empresa',
        ),
        migrations.AddField(
            model_name='consola',
            name='compania',
            field=models.CharField(default='Desconocida', max_length=255),
            preserve_default=False,
        ),
    ]
